### ISSUE TITLE
Pour from the TAP

### ISSUE THREAD

**Issue by mstade** [pemrouz/popper#6]
So I gave this a go, but couldn't quite make things work. It probably didn't help that I'm not using mocha, but rather using [tape](https://github.com/substack/tape) to output a TAP result. It might make the most sense for you to not assume what test harness is being used, but rather just consume TAP results. It seems to be the protocol of choice these days, and there's plenty of tooling available for it.

**Comment by pemrouz** [comment]
Yeah, mocha is a pretty hard assumption for now. Mostly just because of how the test agents [collect the results](https://github.com/pemrouz/popper/blob/master/client.js#L43) and the actual [test harness page served](https://github.com/pemrouz/popper/blob/master/client/test.html). 

Happy to make it test harness agnostic though if you have a specific use case.

**Comment by mstade** [comment]
Well the use case is – I don't use mocha. :o)
Specifically, I'm using tape to produce TAP output, which I then pipe through various utilities to get nice formatting and what not. Mocha can produce TAP output as well, so you wouldn't necessarily be cutting anyone out by having TAP support.

**Comment by pemrouz** [comment]
> Well the use case is – I don't use mocha. :o)

Yeah, I got that part :P I haven't played with tape yet, so meant I'll have to wait to see how your set up looks like after sammyt/rhumb#10 and then think about best way to have popper support it.

**Comment by mstade** [comment]
You got it, I've pushed the tests now. (See sammyt/rhumb#11)

**Comment by pemrouz** [comment]
Right, this should be easier than I thought. Test bundle runs, then just needs to collect the TAP results via the console rather than the DOM. Also need to change the mocha output to TAP, then there will only be one way of collecting results. Will probably pick this up sometime next week if it's not already done by then..

**Comment by mstade** [comment]
Yeah I think that's exactly it. I'll see what damage I can do if you don't get to it first. :o)

**Comment by pemrouz** [comment]
:+1:

**Comment by pemrouz** [comment]
Added support for tape in 0.1.1. You can see an example here (from [vanillacomponents/ux-button](https://github.com/vanillacomponents/ux-button)): 
- [Tape tests](https://github.com/vanillacomponents/ux-button/blob/master/src/test.js)
- [Travis results](https://travis-ci.org/vanillacomponents/ux-button/builds/107574892#L1353)
- [.popper.yml](https://github.com/vanillacomponents/ux-button/blob/master/.popper.yml)

In fact, the `runner` option (via YAML or CLI) is just used to pick out an `index.html` from one of the folders here so it's easy to add more in the future.

@mstade, let me know if this works for you!

**Comment by mstade** [comment]
Very cool! I'll have a look as soon as I get a chance!
